# Cài đặt build cho Netlify
[build]
  # Lệnh để build trang web
  command = "npm run build"
  
  # Thư mục chứa các file sẽ được deploy (vì index.html nằm ở gốc, ta đặt là ".")
  publish = "."
  
  # Thư mục chứa các serverless functions
  functions = "netlify/functions/"

# Quy tắc chuyển hướng cho các ứng dụng trang đơn (SPA)
# Điều này đảm bảo mọi đường dẫn đều được trả về file index.html để React xử lý.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cấu hình cho Netlify Functions
[functions]
  # Cấu hình cụ thể cho hàm 'data'
  [functions.data]
    # Chỉ dẫn cho trình build không gói thư viện 'pg' vào file hàm.
    # Điều này là bắt buộc cho các thư viện có native bindings như 'pg'.
    external_node_modules = ["pg"]